import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
=======
import { Outfit } from "next/font/google";
import "@/app/globals.css";

const outfit = Outfit({
>>>>>>> 8ec0f44 (01 Landing Page Setup)
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
=======
  title: "Code Craft AI",
>>>>>>> 8ec0f44 (01 Landing Page Setup)
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
=======
      <body className={outfit.className}>{children}</body>
>>>>>>> 8ec0f44 (01 Landing Page Setup)
    </html>
  );
}
